#!/usr/bin/env python

from urlparse import urlparse
import socket as skt
import os
import sys
import asyncore

severName = sys.argv[-1]
fileName = sys.argv[-2]
severPort = 8080

host = urlparse(severName).hostname
path = urlparse(severName).path


def get(host, path):
    return ("GET {n} HTTP/1.1\r\n" + "Host: {s}\r\n\r\n").format(s=host, n=path)


print "start"
clientSocket = skt.socket(skt.AF_INET, skt.SOCK_STREAM)
clientSocket.connect((host, severPort))
print "connnect...."
request_str = get(host,path)
clientSocket.send(request_str)

receive = 0
header = ""
with open (fileName, 'wb') as f:
    while True:
        datareceive = clientSocket.recv(1024)
        header += datareceive 
        if "\r\n\r\n" in header:
            headerFinal, remain = header.split("\r\n\r\n")
            receive += len(remain)
            f.write(remain)
            break
     
    # print headerFinal   
    contentLen = headerFinal.split()  
    # print contentLen
    i = 0
    for each in contentLen:
        if each == "Content-Length:":
            cl = contentLen[i+1]
            break
        i += 1

    print cl

    cl = int(cl)
    # print type(cl)
        
    while receive < cl:
        datareceive = clientSocket.recv(1024)
        receive += len(datareceive)
        f.write(datareceive)
        print receive, cl
        # print len(datareceive)
        if not datareceive:
            break
    print 'hello'
    clientSocket.close()

    
# print headerFinal
# print len(receive)
# print len(receive) 


# print contentLen

# for each in receive:
#     header += each
#     if "\r\n\r\n" in header:
#         break

# l = len(header)

# content = receive[l:]

# # print len(content)

# with open('/home/dc/Downloads/tie', 'wb') as f:
#     print 'file open'
#     f.write(content)
# # clientSocket.close()
    
print "finish"